services:
  - type: web
    name: spencer-hub
    runtime: docker
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
